version: "3.2"
services:
  nginx:
    build:
      context: ./nginx
    volumes:
    - ./nginx/sites:/etc/nginx/conf.d/
    ports:
    - '5001:80'
  frontend:
    build:
      context: ./frontend
    volumes:
    - ./frontend:/home/app/frontend
    # - /home/app/frontend/node_modules
    environment:
      NODE_ENV: dev
  backend:
    build:
      context: ./backend
    volumes:
    - ./backend:/home/app/backend
    # - /home/app/frontend/node_modules
    environment:
      NODE_ENV: dev