version: "3.2"
services:
  frontend:
    build:
      context: ./frontend
    ports:
    - '5002:3000'
    volumes:
    - ./frontend:/home/app/frontend
    - /home/app/frontend/node_modules
    environment:
      NODE_ENV: dev